# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
# THIS SCRIPT IS SUPPOSED TO BE AN EXAMPLE. MODIFY IT ACCORDING TO YOUR NEEDS!
sudo: false
language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
notifications:
  email: false
 
# Setup anaconda
before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      export PATH=/home/travis/miniconda2/bin:$PATH;
    else
      export PATH=/home/travis/miniconda3/bin:$PATH;
    fi
  - conda update --yes conda
  - conda install build
  - conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
  - conda install --yes -n condaenv pip
  - conda config --add channels https://conda.anaconda.org/omnia
  - source activate condaenv
# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy algopy pytest
  - pip install coveralls
# - python setup.py install
  - conda build conda_recipe
  - conda install numdifftools --use-local
before_script:
  - git config --global user.email "per.andreas.brodtkorb@gmail.com"
  - git config --global user.name "pbrod"
script:
  - coverage run --source=numdifftools setup.py test
after_success:
  - coveralls
cache:
  - apt
