# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
# THIS SCRIPT IS SUPPOSED TO BE AN EXAMPLE. MODIFY IT ACCORDING TO YOUR NEEDS!
dist: trusty
sudo: required

addons:
  sonarqube:
    token:
      secure: "67bcbf1aefb992993fdd45b78fb4977a05be39b9"
  code_climate:
    repo_token: 9c5d44592ed63ccd3c2b4aabf54fd9aee50f02e21cd016f67f4287e68f708dba
jdk:
  - oraclejdk8

#sudo: false
language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
notifications:
  email: false
 
# Setup anaconda
before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      export PATH=/home/travis/miniconda2/bin:$PATH;
    else
      export PATH=/home/travis/miniconda3/bin:$PATH;
    fi
  - conda update --yes conda
  - conda install --yes conda-build
  - conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
  - conda install --yes -n condaenv pip
  - conda config --add channels https://conda.anaconda.org/omnia
  - conda config --add channels https://conda.anaconda.org/qttesting
  - conda config --add channels https://conda.anaconda.org/pbrod
  - source activate condaenv
# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy algopy pytest statsmodels
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      conda install --yes pyqt=5 matplotlib;
    else
      conda install --yes pyqt=4.11 matplotlib;
    fi
  - pip install coveralls
  - pip install codecov
  - pip install codeclimate-test-reporter
  - pip install hypothesis
  - python setup.py install
#  - conda build conda_recipe
#  - conda install numdifftools --use-local
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - git config --global user.email "per.andreas.brodtkorb@gmail.com"
  - git config --global user.name "pbrod"
script:
  - coverage erase
  - coverage run --source=numdifftools setup.py test
  - coverage xml -o coverage.xml
#  - sed -i 's/filename="/filename=".\//g' coverage.xml
  - CODECLIMATE_REPO_TOKEN=9c5d44592ed63ccd3c2b4aabf54fd9aee50f02e21cd016f67f4287e68f708dba codeclimate-test-reporter
#  - pylint numdifftools -r n --msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}" > pylint-report.txt
  - sonar-scanner -X

after_success:
  - coveralls
  - codecov
cache:
  - apt
cache:
  directories:
    - '$HOME/.sonar/cache'

